include ../_env/env.mk

TARGET       = AutoLoto
SRC          = $(TARGET).c main.c $(ROOT_FOLDER)/Config/Descriptors.c $(LUFA_SRC_USB) $(ROOT_FOLDER)/core/action.c $(ROOT_FOLDER)/core/default_sequences.c $(ROOT_FOLDER)/core/usb_device.c

# Default target
all:

include ../_env/lufa.mk
