include ../_env/env.mk

TARGET       = AutoHost
SRC          = $(TARGET).c main.c $(ROOT_FOLDER)/Config/Descriptors.c $(LUFA_SRC_USB) $(ROOT_FOLDER)/core/action.c $(ROOT_FOLDER)/core/usb_device.c
LUFA_PATH    = $(ROOT_FOLDER)/LUFA

# Default target
all:

include ../_env/lufa.mk
